### ISSUE TITLE
HP Printers List out of range

### ISSUE THREAD

**Issue by jonbrown21** [autopkg/n8felton-recipes#87] opened 2018-08-04 03:06 UTC
Not sure if I am just using this wrong but I keep getting a list out of range error 

```
Processing HPPrinterDrivers.munki.recipe...
com.github.n8felton.shared/HPSoftwareInfoProvider
{'Input': {'product_number': u'E6B70A'}}
HPSoftwareInfoProvider: No value supplied for lang_code, setting default value of: en
HPSoftwareInfoProvider: No value supplied for os, setting default value of: Mac OS X 10.11
HPSoftwareInfoProvider: No value supplied for country_code, setting default value of: us
HPSoftwareInfoProvider: Software URL: https://h20614.www2.hp.com/ediags/solutions/software/v3?ProductNumber=E6B70A&OS=Mac%20OS%20X%2010.11&lc=en&cc=us
{'Output': {'description': u'Installs genuine HP Drivers and HP Utility - essential software for using the features of your HP product.',
            'url': u'ftp://ftp.hp.com/pub/softlib/software12/HP_Quick_Start/osx/Installations/Essentials/hp-printer-essentials-S-5_7_5.pkg',
            'version': u'5.7.5.26'}}
URLDownloader
{'Input': {'url': u'ftp://ftp.hp.com/pub/softlib/software12/HP_Quick_Start/osx/Installations/Essentials/hp-printer-essentials-S-5_7_5.pkg'}}
URLDownloader: No value supplied for CHECK_FILESIZE_ONLY, setting default value of: False
URLDownloader: No value supplied for CURL_PATH, setting default value of: /usr/bin/curl
list index out of range
Failed.
Receipt written to /Users/serveradmin/Library/AutoPkg/Cache/local.munki.HPPrinterDrivers/receipts/HPPrinterDrivers.munki-receipt-20180803-230225.plist

The following recipes failed:
    HPPrinterDrivers.munki.recipe
        Error in local.munki.HPPrinterDrivers: Processor: URLDownloader: Error: list index out of range
```

**Comment by cwhits** [comment] 2018-08-24 20:00
are you still getting this error?

**Comment by n8felton** [comment] 2018-10-03 02:06
Unable to reproduce. Closing issue for now, but please feel free to reopen if it's still happening for you.

**Closed by n8felton** 2018-10-03 02:06 UTC
